import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Header from "@/components/RootLayout/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider {...{ session }}>
        <body>
          <aside></aside>
          <main>
            <Header />
            <div>{children}</div>
          </main>
        </body>
      </SessionProvider>
    </html>
  );
}
