name: Prisma Migrate Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: "npm"

      - name: Install
        run: npm i

      - name: Remove node_modules/.prisma
        run: rm -rf node_modules/.prisma

      - name: Deploy Migrations
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DB_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_DB_URL }}
