name: Prisma Migrate Preview

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - draft
    paths:
      - "./prisma/**/*.*"

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: "npm"

      - name: Install
        run: npm i

      - name: Remove node_modules/.prisma
        run: rm -rf node_modules/.prisma

      - name: Deploy Migrations
        run: npx prisma migrate deploy
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DIRECT_DB_URL: ${{ secrets.DIRECT_DB_URL }}
